version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      # Пример переменных окружения, необходимых вашему приложению
      DB_URL: "jdbc:postgresql://postgres:5432/mydb"
      DB_USER: "postgres"
      DB_PASSWORD: "secret"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  pgdata:
