version: '3.9'
services:
  auth-service:
    build: .
    container_name: auth-service
    # Запустится Dockerfile из текущей директории (где он лежит).
    ports:
      - "8080:8080"
    environment:
      # Задаём переменные окружения,
      # которые ваше приложение сможет читать.
      DB_URL: "jdbc:postgresql://postgres:5432/mydb"
      DB_USER: "postgres"
      DB_PASSWORD: "secret"

    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
